import LeftSideBar from "@/components/LeftSideBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   icons: "@/public/Snapchat-logo.png",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <LeftSideBar />
      {children}
    </div>
  );
}
